USE [master]
GO
/****** Object:  Database [RacedayDb]    Script Date: 9/3/2026 1:30:51 PM ******/
CREATE DATABASE [RacedayDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RacedayDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\RacedayDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RacedayDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\RacedayDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RacedayDb] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RacedayDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RacedayDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RacedayDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RacedayDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RacedayDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RacedayDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [RacedayDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [RacedayDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RacedayDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RacedayDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RacedayDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RacedayDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RacedayDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RacedayDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RacedayDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RacedayDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RacedayDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RacedayDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RacedayDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RacedayDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RacedayDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RacedayDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RacedayDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RacedayDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RacedayDb] SET  MULTI_USER 
GO
ALTER DATABASE [RacedayDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RacedayDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RacedayDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RacedayDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RacedayDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RacedayDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RacedayDb] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [RacedayDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [RacedayDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RacedayDb]
GO
/****** Object:  Table [dbo].[AuthUsers]    Script Date: 9/3/2026 1:30:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuthUsers](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[PasswordHash] [varchar](255) NOT NULL,
	[Email] [varchar](100) NOT NULL,
 CONSTRAINT [PK_AuthUsers] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryID] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Event]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Event](
	[EventID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](255) NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[Location] [varchar](100) NOT NULL,
	[OrganiserID] [int] NOT NULL,
	[CategoryID] [int] NOT NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Organiser]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Organiser](
	[OrganiserID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Organiser] PRIMARY KEY CLUSTERED 
(
	[OrganiserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Participant]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Participant](
	[ParticipantID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[Age] [int] NOT NULL,
	[Location] [varchar](100) NOT NULL,
	[UserID] [int] NULL,
 CONSTRAINT [PK_Participant] PRIMARY KEY CLUSTERED 
(
	[ParticipantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RaceEntries]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RaceEntries](
	[EntryID] [int] IDENTITY(1,1) NOT NULL,
	[ParticipantID] [int] NOT NULL,
	[RaceID] [int] NOT NULL,
	[EventID] [int] NOT NULL,
	[EntryDate] [datetime] NOT NULL,
 CONSTRAINT [PK_RaceEntries] PRIMARY KEY CLUSTERED 
(
	[EntryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Races]    Script Date: 9/3/2026 1:30:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Races](
	[RaceID] [int] IDENTITY(1,1) NOT NULL,
	[RaceName] [varchar](50) NOT NULL,
	[StartTime] [datetime] NOT NULL,
	[EventID] [int] NOT NULL,
 CONSTRAINT [PK_Races] PRIMARY KEY CLUSTERED 
(
	[RaceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Event]  WITH CHECK ADD  CONSTRAINT [FK_Event_Categories] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Categories] ([CategoryID])
GO
ALTER TABLE [dbo].[Event] CHECK CONSTRAINT [FK_Event_Categories]
GO
ALTER TABLE [dbo].[Event]  WITH CHECK ADD  CONSTRAINT [FK_Event_Organiser] FOREIGN KEY([OrganiserID])
REFERENCES [dbo].[Organiser] ([OrganiserID])
GO
ALTER TABLE [dbo].[Event] CHECK CONSTRAINT [FK_Event_Organiser]
GO
ALTER TABLE [dbo].[Participant]  WITH CHECK ADD  CONSTRAINT [FK_Participant_AuthUsers] FOREIGN KEY([UserID])
REFERENCES [dbo].[AuthUsers] ([UserID])
GO
ALTER TABLE [dbo].[Participant] CHECK CONSTRAINT [FK_Participant_AuthUsers]
GO
ALTER TABLE [dbo].[RaceEntries]  WITH CHECK ADD  CONSTRAINT [FK_RaceEntries_Event] FOREIGN KEY([EventID])
REFERENCES [dbo].[Event] ([EventID])
GO
ALTER TABLE [dbo].[RaceEntries] CHECK CONSTRAINT [FK_RaceEntries_Event]
GO
ALTER TABLE [dbo].[RaceEntries]  WITH CHECK ADD  CONSTRAINT [FK_RaceEntries_Participant] FOREIGN KEY([ParticipantID])
REFERENCES [dbo].[Participant] ([ParticipantID])
GO
ALTER TABLE [dbo].[RaceEntries] CHECK CONSTRAINT [FK_RaceEntries_Participant]
GO
ALTER TABLE [dbo].[RaceEntries]  WITH CHECK ADD  CONSTRAINT [FK_RaceEntries_Races] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Races] ([RaceID])
GO
ALTER TABLE [dbo].[RaceEntries] CHECK CONSTRAINT [FK_RaceEntries_Races]
GO
ALTER TABLE [dbo].[Races]  WITH CHECK ADD  CONSTRAINT [FK_Races_Event] FOREIGN KEY([EventID])
REFERENCES [dbo].[Event] ([EventID])
GO
ALTER TABLE [dbo].[Races] CHECK CONSTRAINT [FK_Races_Event]
GO
USE [master]
GO
ALTER DATABASE [RacedayDb] SET  READ_WRITE 
GO
