name: Part 1 Documentation Check

on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository
      - uses: actions/checkout@v4

      # Runs a simple command
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Check if the Projectfiles folder exists
      - name: Check documentation folder
        run: test -d Projectfiles
      # Check if the updated ERD/database SQL file exists
      - name: Check ERD
        run: test -f Projectfiles/Finalupdated.sql
      # Check API document
      - name: Check API Document
        run: test -f Projectfiles/POEPart1APIEndpointtable.pdf
         # Check ERD Document
      - name: Check API Document
        run: test -f Projectfiles/RacedayPOEPart1ERD.pdf

      # Runs multiple commands
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
